spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sns_db
    username: sns_user
    password: sns_pass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  flyway:
    enabled: false

logging:
  level:
    org.springframework: info
